# Generated by Django 5.0 on 2023-12-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate', '0003_rename_streamplatfrom_streamplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchmate.streamplatform'),
            preserve_default=False,
        ),
    ]
