# Generated by Django 5.0 on 2023-12-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
