# Generated by Django 5.0 on 2024-02-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate', '0008_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='reviewer',
        ),
    ]
